### PR TITLE
Feature/design refresh

### PR DESCRIPTION
**Pull request by CoreyGinnivan**
Mostly just UI tweaks to get it mostly "above the fold" and looking a bit nicer.
Still need to update the widget, but I think that's done on the DonorBox site, so will investigate that soon.

- One thing that needs changed is Mike's twitter link the in the footer (if he has one). Just a bit more trustworthy if you link to a social profile or website :) 

**Before:**
Screen Shot 2020-03-28 at 2 27 20 pm

**After**
Screen Shot 2020-03-28 at 3 09 17 pm

### CODE REVIEW

**Comment by CoreyGinnivan** [comment]
Let me know if you hate anything, or want anything changed ^_^

**Comment by alexlouden** [comment]
Looks great - thank you so much! I'll just make a couple of little tweaks to load webfont and fix the donation box overlap on mobile.

**Comment by alexlouden** [comment]
What do you reckon? https://deploy-preview-2--perth-hospital-meals.netlify.com/

**Comment by alexlouden** [comment]
Will pop it live for now, can tweak it if you have any suggestions!

**Comment by CoreyGinnivan** [comment]
Nice one :)

**Pull request merged**
